# Assignment #2: Efficacy Analysis of a Hypothetical Arthritis Drug

**Objective**: In this assignment, your task is to utilize Python programming skills to evaluate the effectiveness of a fictional medication designed to reduce inflammation caused by arthritis flare-ups.

**Background**: Imagine a clinical trial where 60 patients were administered a new drug for arthritis. Data from this trial has been recorded in a series of CSV files. Evaluate the effectiveness of a fictional medication designed to reduce inflammation caused by arthritis flare-ups.

**Data Structure**:
- Each CSV file corresponds to a specific check-in session with the patients.
- There are 12 such CSV files, reflecting 12 different sessions where patients reported their experiences.
- Inside each file:
  - Rows: Each of the 60 rows represents a unique patient.
  - Columns: Each of the 40 columns corresponds to a day, detailing the number of inflammation flare-ups the patient experienced on that day.

**Your Role**: Analyze this data to determine how effective the new drug has been in managing arthritis inflammation across the trial period.

## Submission Information

🚨 **Please review our [Assignment Submission Guide](https://github.com/UofT-DSI/onboarding/blob/main/onboarding_documents/submissions.md)** 🚨 for detailed instructions on how to format, branch, and submit your work. Following these guidelines is crucial for your submissions to be evaluated correctly.

### Submission Parameters:
* Submission Due Date: `11:59 PM - December 8, 2025`
* The branch name for your repo should be: `assignment-2`
* What to submit for this assignment:
    * This Jupyter Notebook (assignment_2.ipynb) should be populated and should be the only change in your pull request.
* What the pull request link should look like for this assignment: `https://github.com/<your_github_username>/python/pull/<pr_id>`
    * Open a private window in your browser. Copy and paste the link to your pull request into the address bar. Make sure you can see your pull request properly. This helps the technical facilitator and learning support staff review your submission easily.

Checklist:
- [ ] Created a branch with the correct naming convention.
- [ ] Ensured that the repository is public.
- [ ] Reviewed the PR description guidelines and adhered to them.
- [ ] Verify that the link is accessible in a private browser window.

If you encounter any difficulties or have questions, please don't hesitate to reach out to our team via our Slack at `#dc-help`. Our Technical Facilitators and Learning Support staff are here to help you navigate any challenges.

**The file is located under `python/05_src/data/assignment_2_data/`. The filtered list has been made for you `all_paths` below.**



## 1. Reading and Displaying Data from the First File

With the list of the relevant `inflammation_xx.csv` file paths above, write a program to read the `inflammation_xx.csv` files, and display the contents of the first file in this list.

**Hint**: Remember to use appropriate Python file handling and data reading methods. If you need guidance on how to handle CSV files in Python, refer to the relevant sections in your Python learning resources.

In [128]:
all_paths = [
  "../../05_src/data/assignment_2_data/inflammation_01.csv",
  "../../05_src/data/assignment_2_data/inflammation_02.csv",
  "../../05_src/data/assignment_2_data/inflammation_03.csv",
  "../../05_src/data/assignment_2_data/inflammation_04.csv",
  "../../05_src/data/assignment_2_data/inflammation_05.csv",
  "../../05_src/data/assignment_2_data/inflammation_06.csv",
  "../../05_src/data/assignment_2_data/inflammation_07.csv",
  "../../05_src/data/assignment_2_data/inflammation_08.csv",
  "../../05_src/data/assignment_2_data/inflammation_09.csv",
  "../../05_src/data/assignment_2_data/inflammation_10.csv",
  "../../05_src/data/assignment_2_data/inflammation_11.csv",
  "../../05_src/data/assignment_2_data/inflammation_12.csv"
]

with open(all_paths[11], 'r') as f:
    # YOUR CODE HERE: Use the readline() or readlines() method to read the .csv file into a variable
    lines = f.readlines() #read all the lines in the file through readlines() function
    print ("all lines as a single varibale")
    print(lines) # print all lines as a single variable
    print ("The first line as a single varibale")
    print(lines[0]) # print the first line
    print ("The 10th line as a single varibale")
    print(lines[9]) # print the 10th line
    # YOUR CODE HERE: Iterate through the variable using a for loop and print each row for inspection
    print ("Printing every line from the file using loop")
    for line in lines:   # using a for loop to read each line
      print(line)        # printing one line at a time

all lines as a single varibale
['0,0,2,3,3,1,6,6,3,6,10,6,8,5,5,8,16,12,13,5,13,18,11,12,11,9,10,13,9,4,4,7,7,3,1,5,3,1,1,1\n', '0,1,0,1,1,1,1,1,7,7,4,2,7,8,4,6,16,17,13,5,17,5,17,8,5,10,3,5,5,5,8,9,4,4,3,4,1,3,0,0\n', '0,1,2,0,4,5,6,2,5,3,8,3,8,11,7,9,7,4,8,11,5,18,4,5,6,6,5,13,7,4,7,9,4,3,5,5,2,2,2,1\n', '0,0,2,0,3,2,6,7,5,6,8,5,8,11,13,8,5,11,10,11,9,12,17,5,4,15,7,5,11,3,5,8,4,4,5,4,2,0,2,1\n', '0,1,1,3,3,1,1,3,4,3,6,3,9,6,6,7,5,15,18,4,9,12,9,4,9,4,9,11,10,8,10,2,6,1,6,4,4,2,0,1\n', '0,1,0,0,4,2,2,4,4,6,5,9,8,3,14,11,5,7,5,14,9,7,15,10,11,5,11,12,4,7,10,6,6,2,6,3,4,0,2,1\n', '0,1,2,1,3,1,5,3,8,6,3,3,12,13,12,6,15,10,5,4,16,10,12,14,15,10,6,4,8,7,7,4,5,4,3,5,4,0,0,0\n', '0,1,1,0,4,5,5,2,7,5,3,5,3,8,11,13,15,9,14,19,16,11,10,17,7,8,3,7,8,9,9,5,4,2,4,1,4,3,1,0\n', '0,0,2,2,3,5,1,4,6,4,7,7,3,13,7,3,7,6,18,18,10,12,17,8,7,15,13,13,11,4,9,9,8,1,3,1,4,2,1,1\n', '0,0,1,2,4,5,1,7,7,7,8,2,8,13,10,10,5,16,17,13,8,6,9,5,11,15,5,6,5,10,2,3,8,4,6,4,2,2,0,1\n', '0,0,2,3,3,2,3,4,8,7,6,11,5,6,8,8,

## 2. Data Summarization Function: `patient_summary`

Your next step is to create a function named `patient_summary` that will compute summary statistics for each patient's data over a 40-day period.

**Function Specifications**:
- **Function Name**: `patient_summary`
- **Parameters**:
  1. `file_path`: A string representing the path to the CSV file containing the patient data.
  2. `operation`: A string specifying the type of summary operation to perform. Acceptable values are "mean", "max", or "min". This will determine whether the function calculates the average, maximum, or minimum number of flare-ups for each patient over the 40 days.

**Expected Behavior**:
- Your function should read the data from the file at `file_path`.
- Perform the specified `operation` (mean, max, or min) to summarize the flare-ups data for each of the 60 patients.
- Return an array with 60 elements, each element being the result of the summary operation for a corresponding patient.

**Expected Output**:
- The output should be an array with a length of 60, aligning with the number of patients in the study.

**Hints for Implementation**:
1. **Utilizing NumPy**: For efficient data manipulation and computation, consider using NumPy, as discussed in the `10_numpy` slides.
2. **Output Shape**: Ensure that the shape of your output data matches the number of patients, which is 60.

In [124]:
import numpy as np

def patient_summary(file_path, operation):
    data = np.loadtxt(fname=file_path, delimiter=',') # Load the data from the file
    ax = 1  # This specifies that the operation should be done for each row (patient)

    # Implement the specific operation based on the 'operation' argument
    if operation == 'mean':
        # YOUR CODE HERE: Calculate the mean (average) number of flare-ups for each patient
        summary_values = np.mean(data, axis = ax) 
    elif operation == 'max':
        # YOUR CODE HERE: Calculate the maximum number of flare-ups experienced by each patient
        summary_values = np.max(data, axis = ax)
    elif operation == 'min':
        # YOUR CODE HERE: Calculate the minimum number of flare-ups experienced by each patient
        summary_values = np.min(data, axis = ax)
    elif operation == "all":
        #creating an option to get all summary measures together
        summary_values1 = np.mean(data, axis = ax)
        summary_values2 = np.max(data, axis = ax)
        summary_values3 = np.min(data, axis = ax)
        summary_values = np.column_stack((summary_values1, summary_values2, summary_values3))
    else:
        # If the operation is not one of the expected values, raise an error
        raise ValueError("Invalid operation. Please choose 'mean', 'max', or 'min', or 'all'.")

    return summary_values

In [123]:
# Test it out on the data file we read in and make sure the size is what we expect i.e., 60
# Your output for the first file should be 60
data_min = patient_summary(all_paths[11], 'min')
print(len(data_min))

60


In [122]:
# testing patient_summary - min - result of output
data_min = patient_summary(all_paths[7], 'min')
data_min

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.,
       0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [121]:
# testing patient_summary - max - length of out output
data_max = patient_summary(all_paths[4], 'max')
print(len(data_max))

60


In [120]:
# testing patient_summary - max - result of output
data_max = patient_summary(all_paths[1], 'max')
data_max

array([15., 15., 18., 18., 19., 18., 17., 14., 14., 18., 15., 18., 19.,
       19., 17., 17., 15., 17., 20., 14., 14., 14., 19., 16., 17., 17.,
       14., 14., 15., 19., 17., 18., 19., 15., 19., 15., 17., 16., 20.,
       16., 17., 18., 18., 19., 17., 17., 18., 18., 17., 19., 15., 18.,
       14., 17., 19., 16., 17., 19., 20., 18.])

In [119]:
# testing patient_summary - mean - length of out output
data_mean = patient_summary(all_paths[2], 'mean')
print(len(data_mean))

60


In [118]:
# testing patient_summary - mean - result of output
data_mean = patient_summary(all_paths[10], "mean")
data_mean

array([4.   , 4.225, 3.9  , 3.7  , 4.075, 3.95 , 4.55 , 3.45 , 3.975,
       4.525, 4.425, 4.225, 3.85 , 4.925, 4.5  , 3.225, 4.4  , 4.275,
       4.5  , 4.125, 4.7  , 5.9  , 3.975, 4.   , 5.275, 4.075, 4.475,
       3.7  , 3.775, 3.7  , 3.925, 4.525, 4.125, 4.025, 4.1  , 4.675,
       5.025, 4.9  , 4.7  , 4.75 , 3.975, 5.325, 3.925, 4.4  , 4.35 ,
       4.65 , 4.1  , 4.   , 4.4  , 4.575, 3.9  , 4.65 , 3.725, 4.   ,
       4.   , 5.2  , 4.325, 3.575, 4.075, 0.   ])

In [117]:
#testing patient_summary - all - length of output
data_all = patient_summary(all_paths[0], 'all')
print(len(data_all))

60


In [115]:
# testing patient_summary - all - result of output
data_all = patient_summary(all_paths[6], "all")
data_all

array([[ 5.075, 18.   ,  0.   ],
       [ 5.875, 16.   ,  0.   ],
       [ 5.85 , 14.   ,  0.   ],
       [ 6.225, 18.   ,  0.   ],
       [ 5.475, 17.   ,  0.   ],
       [ 5.875, 17.   ,  0.   ],
       [ 5.475, 19.   ,  0.   ],
       [ 5.85 , 18.   ,  0.   ],
       [ 5.625, 16.   ,  0.   ],
       [ 6.25 , 17.   ,  0.   ],
       [ 5.525, 14.   ,  0.   ],
       [ 5.7  , 16.   ,  0.   ],
       [ 6.625, 18.   ,  0.   ],
       [ 5.95 , 17.   ,  0.   ],
       [ 5.75 , 19.   ,  0.   ],
       [ 5.   , 13.   ,  0.   ],
       [ 5.875, 16.   ,  0.   ],
       [ 6.5  , 17.   ,  0.   ],
       [ 5.675, 17.   ,  0.   ],
       [ 6.35 , 20.   ,  0.   ],
       [ 6.25 , 20.   ,  0.   ],
       [ 5.45 , 16.   ,  0.   ],
       [ 6.1  , 16.   ,  0.   ],
       [ 7.075, 20.   ,  0.   ],
       [ 6.175, 17.   ,  0.   ],
       [ 5.975, 19.   ,  0.   ],
       [ 6.275, 19.   ,  0.   ],
       [ 6.475, 19.   ,  0.   ],
       [ 6.325, 17.   ,  0.   ],
       [ 6.325, 19.   ,  0.   ],
       [ 5

In [114]:
# testing patient_summary - median - it should result in error message specified within function
data_median = patient_summary(all_paths[6], "median")

ValueError: Invalid operation. Please choose 'mean', 'max', or 'min', or 'all'.

## 3. Error Detection in Patient Data

Your final task is to develop a function named `detect_problems` that identifies any irregularities in the patient data, specifically focusing on detecting patients with a mean inflammation score of 0.

**Function Specifications**:
- **Function Name**: `detect_problems`
- **Parameter**:
  - `file_path`: A string that specifies the path to the CSV file containing patient data.

**Expected Behavior**:
- The function should read the patient data from the file at `file_path`.
- Utilize the previously defined `patient_summary()` function to calculate the mean inflammation for each patient.
- Employ an additional helper function `check_zeros(x)` (provided) to determine if there are any zero values in the array of mean inflammations.
- The `detect_problems()` function should return `True` if there is at least one patient with a mean inflammation score of 0, and `False` otherwise.

**Hints for Implementation**:
1. Call `patient_summary(file_path, 'mean')` to get the mean inflammation scores for all patients.
2. Use `check_zeros()` to evaluate the mean scores. This helper function takes an array as input and returns `True` if it finds zero values in the array.
3. Based on the output from `check_zeros()`, the `detect_problems()` function should return `True` (indicating an issue) if any mean inflammation scores of 0 are found, or `False` if none are found.

**Note**: This function is crucial for identifying potential data entry errors, such as healthy individuals being mistakenly included in the dataset or other data-related issues.

**Understanding the `check_zeros(x)` Helper Function**

The `check_zeros(x)` function is provided as a tool to assist with your data analysis. While you do not need to modify or fully understand the internal workings of this function, it's important to grasp its input, output, and what the output signifies:

1. **Input**:
   - **Parameter `x`**: This function takes an array of numbers as its input. In the context of your assignment, this array will typically represent a set of data points from your patient data, such as mean inflammation scores.

2. **Output**:
   - The function returns a boolean value: either `True` or `False`.

3. **Interpreting the Output**:
   - **Output is `True`**: This indicates that the array `x` contains at least one zero value. In the context of your analysis, this means that at least one patient has a mean inflammation score of 0, signaling a potential issue or anomaly in the data.
   - **Output is `False`**: This signifies that there are no zero values in the array `x`. For your patient data, it means no patient has a mean inflammation score of 0, and thus no apparent anomalies of this type were detected.

**Usage in Your Analysis**:
When using `check_zeros(x)` in conjunction with your `patient_summary()` function in the `detect_problems()` function, you'll be checking whether any patient in your dataset has an average (mean) inflammation score of 0.

In [113]:
# Run this cell so you can use this helper function

def check_zeros(x):
    '''
    Given an array, x, check whether any values in x equal 0.
    Return True if any values found, else returns False.
    '''
    # np.where() checks every value in x against the condition (x == 0) and returns a tuple of indices where it was True (i.e. x was 0)
    flag = np.where(x == 0)[0]

    # Checks if there are any objects in flag (i.e. not empty)
    # If not empty, it found at least one zero so flag is True, and vice-versa.
    return len(flag) > 0

In [112]:
# Define your function `detect_problems` here

def detect_problems(file_path):
  #YOUR CODE HERE: Use patient_summary() to get the means and check_zeros() to check for zeros in the means
  data_mean = patient_summary(file_path, 'mean')
  return check_zeros(data_mean)

In [111]:
# Test out your code here
# Your output for the first file should be False
print(detect_problems(all_paths[0]))

False


In [110]:
# files 3,  8 and 11 have pts with avg value = 0 
print(detect_problems(all_paths[2])) # output should be True

True


In [109]:
# files 3,  8 and 11 have pts with avg value = 0 
print(detect_problems(all_paths[7]))  # output should be True

True


In [108]:
# files 3,  8 and 11 have pts with avg value = 0 
print(detect_problems(all_paths[10])) # output should be True

True


In [ ]:
# checking patient_summary output - file number 3 to confirm 0 in the array
data_mean = patient_summary(all_paths[2], "mean")
data_mean

array([4.   , 4.225, 3.9  , 3.7  , 4.075, 3.95 , 4.55 , 3.45 , 3.975,
       4.525, 4.425, 4.225, 3.85 , 4.925, 4.5  , 3.225, 4.4  , 4.275,
       4.5  , 4.125, 4.7  , 5.9  , 3.975, 4.   , 5.275, 4.075, 4.475,
       3.7  , 3.775, 3.7  , 3.925, 4.525, 4.125, 4.025, 4.1  , 4.675,
       5.025, 4.9  , 4.7  , 4.75 , 3.975, 5.325, 3.925, 4.4  , 4.35 ,
       4.65 , 4.1  , 4.   , 4.4  , 4.575, 3.9  , 4.65 , 3.725, 4.   ,
       4.   , 5.2  , 4.325, 3.575, 4.075, 0.   ])

In [ ]:
# checking patient_summary output - file number 8 to confirm 0 in the array 
data_mean = patient_summary(all_paths[7], "mean")
data_mean

array([4.   , 4.225, 3.9  , 3.7  , 4.075, 3.95 , 4.55 , 3.45 , 3.975,
       4.525, 4.425, 4.225, 3.85 , 4.925, 4.5  , 3.225, 4.4  , 4.275,
       4.5  , 4.125, 4.7  , 5.9  , 3.975, 4.   , 5.275, 4.075, 4.475,
       3.7  , 3.775, 3.7  , 3.925, 4.525, 4.125, 4.025, 4.1  , 4.675,
       5.025, 4.9  , 4.7  , 4.75 , 3.975, 5.325, 3.925, 4.4  , 4.35 ,
       4.65 , 4.1  , 4.   , 4.4  , 4.575, 3.9  , 4.65 , 3.725, 4.   ,
       4.   , 5.2  , 4.325, 3.575, 4.075, 0.   ])

In [ ]:
# checking patient_summary output - file number 11 to confirm 0 in the array 
data_mean = patient_summary(all_paths[10], "mean")
data_mean

array([4.   , 4.225, 3.9  , 3.7  , 4.075, 3.95 , 4.55 , 3.45 , 3.975,
       4.525, 4.425, 4.225, 3.85 , 4.925, 4.5  , 3.225, 4.4  , 4.275,
       4.5  , 4.125, 4.7  , 5.9  , 3.975, 4.   , 5.275, 4.075, 4.475,
       3.7  , 3.775, 3.7  , 3.925, 4.525, 4.125, 4.025, 4.1  , 4.675,
       5.025, 4.9  , 4.7  , 4.75 , 3.975, 5.325, 3.925, 4.4  , 4.35 ,
       4.65 , 4.1  , 4.   , 4.4  , 4.575, 3.9  , 4.65 , 3.725, 4.   ,
       4.   , 5.2  , 4.325, 3.575, 4.075, 0.   ])

| Criteria                     | Complete Criteria                                                                                                                                                                 | Incomplete Criteria                                                                                                         |
|------------------------------|-------------------------------------------------------------------------------------------------------------------------------------------------------------------------------|-----------------------------------------------------------------------------------------------------------------------|
| **General Criteria**         |                                                                                                                                                                               |                                                                                                                       |
| Code Execution               | All code cells execute without errors.                                                                                                                                        | Any code cell produces an error upon execution.                                                                      |
| Code Quality                 | Code is well-organized, concise, and includes necessary comments for clarity.                                                                                                 | Code is unorganized, verbose, or lacks necessary comments.                                                            |
| Data Handling                | Data files are correctly handled and processed.                                                                                                                               | Data files are not handled or processed correctly.                                                                    |
| Adherence to Instructions    | Follows all instructions and requirements as per the assignment.                                                                                                              | Misses or incorrectly implements one or more of the assignment requirements.                                         |
| **Specific Criteria**        |                                                                                                                                                                               |                                                                                                                       |
| 1. Reading in our files | Correctly prints out information from the first file.                                                  | Fails to print out information from the first file.                              |
| 2. Summarizing our data | Correctly defines `patient_summary()` function. Function processes data as per `operation` and outputs correctly shaped data (60 entries).                                   | Incomplete or incorrect definition of `patient_summary()`. Incorrect implementation of operation or wrong output shape.|
| 3. Checking for Errors  | Correctly defines `detect_problems()` function. Function uses `patient_summary()` and `check_zeros()` to identify mean inflammation of 0 accurately.                        | Incorrect definition or implementation of `detect_problems()` function. Fails to accurately identify mean inflammation of 0.|
| **Overall Assessment**       | Meets all the general and specific criteria, indicating a strong understanding of the assignment objectives.                                                                  | Fails to meet one or more of the general or specific criteria, indicating a need for further learning or clarification.|


## References

### Data Sources
- Software Carpentry. _Python Novice Inflammation Data_. http://swcarpentry.github.io/python-novice-inflammation/data/python-novice-inflammation-data.zip
